version: '3'

services:
  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --workers 2
        --access-logfile -
        --reload
        "app:app"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - './server:/usr/src/app'
    ports:
      - '8000:8000'
